### ISSUE TITLE
Окно уведомления.

### ISSUE THREAD

**Issue by glagius** [hexlet-codebattle/chrome_extension#19]
Такие события как "начало турнира", либо когда кто-то вступил в созданную пользователем игру, надо показывать особым способом. Лучше всего, если это будет нативное уведомление.
Информация для ознакомления. https://developer.chrome.com/extensions/desktop_notifications

**Comment by BabayevEldar** [comment]
Добавил прототип.
Надо допилить, когда будет возможность регистрации пользователя.
Уточнить API с бекендом.

**Comment by H9ko** [comment]
Добавил проверку состояния из настроек

**Comment by H9ko** [comment]
добавлено уведомление о новой игре с кнопочкой join
